name: Automatically labeling pull request.

on:
  pull_request:
    types: [opened]

jobs:
  auto-labeling-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      TZ: 'Asia/Tokyo'

    steps:
      - uses: actions/checkout@v3

      # ãƒ©ãƒ™ãƒ«åã‚’å–å¾—ã™ã‚‹
      - name: Get label name
        id: label_name
        run: |
          branch_type=$(echo ${{github.head_ref}} | cut -d "/" -f1)
          if [ $branch_type == 'feature' ]; then
            label_name=$(echo "enhancement")
          elif [ $branch_type == 'fix' ] || [ $branch_type == 'hotfix' ]; then
            label_name=$(echo "bug")
          else
            label_name=""
          fi
          echo "::set-output name=label_name::$label_name"

      # PRã«ãƒ©ãƒ™ãƒ«ã‚’ä»˜ä¸ã™ã‚‹
      - name: Auto labeling
        if: ${{ steps.label_name.outputs.label_name }}
        run: |
          number=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          gh pr edit $number --add-label ${{ steps.label_name.outputs.label_name }}

    changelog:
      exclude:
        # ãƒªãƒªãƒ¼ã‚¹ãƒãƒ¼ãƒˆã‹ã‚‰é™¤å¤–ã—ãŸã„ãƒ¦ãƒ¼ã‚¶ãƒ¼
        authors:
          - github-actions # <-- è¿½åŠ 
      categories:
        - title: New Features ğŸ‰
          labels:
            - "enhancement"
        - title: Bug Fix ğŸ’Š
          labels:
            - "bug"
        - title: Other Changes ğŸ› 
          labels:
            - "*"